# Generated by Django 3.0.6 on 2020-05-08 09:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms')], default='Ms', max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('add', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
